### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by barryjenkin** [kunjsharma/adapt-scenario#1]
Hi there.
This sounds good. Is it still in development? I get an error when trying to upload to AT, one with framework 2.3.3 and another with 4.2.0.

**Comment by kunjsharma** [comment]
Hi Barry,
Thank you. Yes. properties.schema not updated (contributors are welcome) so won't work with authoring tool. Updated bower details just now. If not install with CLI, use zip and can use with latest framework.

**Comment by kunjsharma** [comment]
Hi Barry, are you able to install now? Please confirm so close this issue.

**Comment by barryjenkin** [comment]
I only have the two instances installed at the moment (fw 2.3.3 and 4.2.0). The latest zip (tested today) is still showing plugin failed error when uploading to both. Will install new AT/framework soon and let you know.

**Comment by kunjsharma** [comment]
Framework:
 ~ v4.0.2 Build for - tested both installations, Adapt CLI and zip.
 ~ v2.3.3 Won't install with CLI, but use zip, and it works.
AT:
 ~ properties.schema file updated, please try now.

**Comment by barryjenkin** [comment]
It's still giving me the upload error (via the AT zip method). 
The versions I'm using: 
- AT 0.6.5 with fw 2.3.3
- AT  0.8.0 with fw 4.2.0

**Comment by kunjsharma** [comment]
Hi Barry, sorry for inconvenience. I setup AT and see the issue, use with framework till then if possible.
